insert into category(description) values ('american')
insert into category(description) values ('mexican')
insert into unit_of_measure(abbreviation) values ('teaspoon')
insert into unit_of_measure(abbreviation) values ('tablespoon')
insert into unit_of_measure(abbreviation) values ('dash')